import React, { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";

import Aos from "aos";
import "aos/dist/aos.css";
import "bootstrap/dist/css/bootstrap.css";

import cv from "./cv.json";
import profil from "../assets/photos/profil.jpeg";
import styles from "../styles/Home.module.css";

import Education from "../components/education";
import Work from "../components/work";
import Skills from "../components/skills";
import Header from "../components/header";

export default function Home() {
  useEffect(() => {
    //import("bootstrap/dist/js/bootstrap");
    Aos.init({ duration: 500 });
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Vy Hong</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main id="home" className={styles.main}>
        <div className={styles.topContainer}>
          <Header />
          <div className={styles.topContent}>
            <span>
              <h1>Hello, I am Vy </h1>
              <h5 className="text-muted">
                Student in Information Systems
                <br /> at Technical University München
              </h5>
            </span>
            <span style={{ alignSelf: "center" }}>
              <Image src={profil} alt="Profil" width={200} height={200} />
            </span>
          </div>
        </div>

        <div id="work" className={styles.workingContainer}>
          <h2
            style={{
              marginBottom: 20,
            }}
          >
            Working Experience
          </h2>
          {cv.work.map((item) => (
            <Work key={item.headline} {...item} />
          ))}
        </div>

        <div id="education" className={styles.educationContainer}>
          <h2
            style={{
              marginBottom: 20,
            }}
          >
            Education
          </h2>
          {cv.education.map((item) => (
            <Education key={item.headline} {...item} />
          ))}
        </div>

        <div id="skills" data-aos="fade-up" className={styles.skillsContainer}>
          <h2 style={{ textAlign: "center", marginBottom: 20 }}>Skills</h2>
          <div className={styles.skillCategoryContainer}>
            <div
              className="card-colums"
              style={{
                width: "13rem",
                flex: 1,
              }}
            >
              <h4>Coding</h4>
              {cv.skills.coding.map((item) => (
                <Skills key={item.headline} {...item} />
              ))}
            </div>
            <div
              className="card-colums"
              style={{
                width: "13rem",
                marginLeft: "1rem",
                marginRight: "1rem",
                flex: 1,
              }}
            >
              <h4>Language</h4>
              {cv.skills.languages.map((item) => (
                <Skills key={item.headline} {...item} />
              ))}
            </div>
            <div
              className="card-colums"
              style={{
                width: "13rem",
                flex: 1,
              }}
            >
              <h4>EDV</h4>
              {cv.skills.EDV.map((item) => (
                <Skills key={item.headline} {...item} />
              ))}
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
